version: '3.7'

services:

  # ivy
  ivy:
    build: ivy/.
    ports:
      - 8080:8080
    volumes:
      # ivy config
      - ./ivy/ivy.yaml:/etc/axonivy-engine/ivy.yaml

      # log4j2 config
      - ./ivy/log4j2.xml:/etc/axonivy-engine/log4j2.xml

      # limited demo license
      - ./ivy/license.lic:/etc/axonivy-engine/license.lic

      # patch your engine
      #- "./patch.jar:/usr/lib/axonivy-engine/patches/service-manager-patch.jar"
      
  # reverse proy
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs

  # system db
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
